version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pinpoint-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./pinpoint.db
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - ADMIN_EMAIL=kaxorovorif6@gmail.com
      - ADMIN_PASSWORD=azam_770
    volumes:
      - ./backend:/app
    restart: unless-stopped
